Repository Team-MID-in-SKHU/MID-Backend, pull requests merged in 2024-06, with the labels that each got.

#60 Feature#46 EventPushAlarmSchedulerService
  .DS_Store
  .github/.DS_Store
  MID_SKHU/.DS_Store
  MID_SKHU/src/.DS_Store
  MID_SKHU/src/main/.DS_Store
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/fcm/FcmController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/todo/UserTodoController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/EventRepository.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/StudentRepository.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/fcm/EventPushAlarmSchedulerService.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/fcm/FirebaseCloudMessageServiceImpl.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/fcm/StudentTodayTodoListIsExitServiceImpl.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/fcm/alarmInterface/FirebaseCloudMessageService.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/fcm/alarmInterface/StudentTodayTodoListIsExitService.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/fcm/alarmInterface/UserTodayTodoListCheckService.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/todo/UserTodayTodoListCheckServiceImpl.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/global/exception/ErrorCode.java
Labels: Feature, 우진

#62 Feature#8 add Student Entity Column
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/fcm/FcmController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/auth/requestDto/SignUpRequestDto.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/user/responseDto/UserDetailsResponseDto.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/user/responseDto/UserInfoResponseDto.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/student/Student.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/auth/SignUpService.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/user/UserDetailsService.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/user/UserInfoService.java
Labels: Setting, 우진, FIx

#63 [feature] #45 userAccount api
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/user/UserAccountController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/user/UserDetailsController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/user/UserInfoController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/TokenBlacklistRepository.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/user/UserAccountService.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/global/config/RedisConfig.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/global/config/SecurityConfig.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/global/jwt/TokenProvider.java
Labels: Feature, 두오

#66 [feature] #65 eventDisplay api
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/event/EventDisplayController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/EventRepository.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/event/EventDisplayService.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/event/EventSearchService.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/event/RandomEventDisplayService.java
Labels: Feature, 두오

#69 [feature] #68 interestUpdate api
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/interest/InterestController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/interest/requestDto/InterestUpdateRequestDto.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/interest/responseDto/InterestUpdateResponseDto.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/interest/InterestUpdateService.java
Labels: Feature, 두오

#71 [Refactor] #70 final refactoring
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/auth/AuthController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/s3/S3Controller.java
Labels: Refactor, Setting, 우진, FIx
