Repository Team-MID-in-SKHU/MID-Backend, pull requests merged in 2024-05, with the labels that each got.

#29 [feature] #25 sms certification api
  MID_SKHU/build.gradle
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/user/SmsCertificationController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/user/UserSmsDto.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/SmsCertificationDao.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/user/UserCertificationService.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/user/UserCertificationServiceImpl.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/global/aop/TimeTraceAop.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/global/common/dto/ApiResponseTemplate.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/global/config/RedisConfig.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/global/exception/ErrorCode.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/global/exception/SuccessCode.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/global/util/SmsCertificationUtil.java
  MID_SKHU/src/main/resources/application.yml
Labels: Feature, 우진

#32 [feature] #31 userInfo api
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/user/UserInfoController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/user/responseDto/UserInfoResponseDto.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/user/UserInfoService.java
Labels: Feature, 두오

#40 [Feature] #39 development of Api Search For Event
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/event/EventCreateForAdminController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/event/EventForUserController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/event/requestDto/EventSearchRequestDto.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/event/responseDto/EventSearchResponseDto.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/event/Event.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/interest/Interest.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/interest/InterestCategory.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/student/Student.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/EventRepository.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/specification/EventSpecification.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/event/EventCreateForAdminService.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/event/EventSearchService.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/user/UserTodoListCheckService.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/global/exception/ErrorCode.java
Labels: Feature, 우진

#42 style: controller code style unify
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/auth/AuthController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/user/UserInfoController.java
Labels: Docs, 우진

#44 [feature] #43 userDetails api
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/user/UserDetailsController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/user/requestDto/UserDetailsUpdateRequestDto.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/user/responseDto/UserDetailsResponseDto.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/student/Student.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/user/UserDetailsService.java
Labels: Feature, 두오

#48 [Feature] #46 fcm base setting
  MID_SKHU/build.gradle
  MID_SKHU/src/main/java/com/skhu/mid_skhu/MidSkhuApplication.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/fcm/FcmController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/fcm/FcmMessage.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/fcm/FcmRequestDto.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/student/Student.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/EventRepository.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/StudentRepository.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/fcm/EventPushAlarmSchedulerService.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/fcm/FirebaseCloudMessageService.java
  MID_SKHU/src/main/resources/application.yml
Labels: Feature, Setting, 우진

#50 Fix#47 UserTodoListCheck API
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/todo/UserTodoController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/controller/user/UserInfoController.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/todo/requestDto/CheckMonthTodoListRequestDto.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/entity/student/Student.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/repository/EventRepository.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/todo/UserMonthTodoListCheckService.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/todo/UserTodayTodoListCheckService.java
Labels: Feature, 우진, FIx

#51 Fix#49 Add FcmToken during SignUp, Login process
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/auth/requestDto/LoginRequestDto.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/dto/auth/requestDto/SignUpRequestDto.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/auth/SignUpService.java
Labels: Refactor, 우진, FIx

#52 delete commentary, an unnecessary line
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/auth/LoginService.java
  MID_SKHU/src/main/java/com/skhu/mid_skhu/app/service/fcm/EventPushAlarmSchedulerService.java
Labels: Docs

#53 modify swagger config description
  MID_SKHU/src/main/java/com/skhu/mid_skhu/global/config/SwaggerApiConfig.java
Labels: Docs

#56 [chore] #46 modify docker image yml
  .github/workflows/build.yml
Labels: Bug, Setting, 우진

#58 chore: modify docker image yml3
  .github/workflows/build.yml
Labels: Bug, Setting, 우진

#59 chore: modify docker image yml4
  .github/workflows/build.yml
Labels: Bug, Setting, 우진
